FROM --platform=linux/amd64 python:3.10-slim
COPY . /app
WORKDIR /app
#COPY . .
#ADD Callahan_Portfolio.py . 
#ADD crash_data_prepped.csv .
#ADD pages/1_Project:_Agglomerative_Clustering_App.py . 
#ADD pages/2_Project:_Rshiny_App_Car_Prices.py . 
#ADD IMG_5550.jpeg . 
#ADD Callahan_resume_07_2024_consulting.pdf . 
#ADD Callahan_resume_07_2024_consulting.docx .
COPY requirements.txt .
RUN pip3 install -r requirements.txt --no-cache-dir
EXPOSE 8501
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "Callahan_Portfolio.py", "--server.port=8501", "--server.address=0.0.0.0"]