FROM --platform=linux/amd64 python:3.10-slim
COPY . /app
WORKDIR /app
COPY requirements.txt .
ENV API_KEY = '069d95d4510c4485b155a1e93570a43a'
ENV endpoint = 'https://openllm-streamlitapp.openai.azure.com/'
ENV deployment_name = 'gpt-35-turbo_for_table_topics'
RUN pip3 install -r requirements.txt --no-cache-dir
EXPOSE 8501
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "Callahan_Portfolio.py", "--server.port=8501", "--server.address=0.0.0.0"]