FROM --platform=linux/amd64 python:3.10-slim
COPY . /app
WORKDIR /app
COPY requirements.txt .
RUN pip3 install -r requirements.txt --no-cache-dir
EXPOSE 8501
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "Callahan_Portfolio.py", "--server.port=8501", "--server.address=0.0.0.0"]